### Datasets explored

#### 1
The first dataset was `Huge Stock Market Dataset` found here: https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs

This looked promising as it contained the information for all US based stocks and ETFs trading on the NYSE, NASDAQ, and NYSE MKT, but after inspecting the data in the dataset, I found it was last updated in November of 2017. This could still be a useful dataset of course, but if we can find a set that includes the most recent years as well I believe any resulting models would be more accurate.

#### 2
The next dataset I came across after finding the first and then looking for something similar but including more recent data was `Stock Market Data (NASDAQ, NYSE, S&P500)` found here: https://www.kaggle.com/paultimothymooney/stock-market-data

I noticed this was the same exchanges we are interested in getting the data for (minus the S&P500 which is just a compilation of stocks from the exchanges themselves) and the description of the dataset said it was updated weekly. This seemed to solve my original problem of wanting additional years of data, but upon inspecting the dataset it appears to be missing many funds that were available in the first.

The first dataset had 8,539 total stocks & ETFs in it, but this second dataset had 3,022.

Even worse than missing out on the most recent few years of information would be to exclude a majority of the stocks & ETFs entirely, so we continue our search.

#### 3
The final dataset I found, called `Stock Market Dataset` found here: https://www.kaggle.com/jacksoncrow/stock-market-dataset, looked to be very similar to the first one, this one having 8,049 unique ticker symbols, but was updated in April of 2020. 

As it is, this dataset appears to be the best, and is recent enough; however, I found in the description an explanation of how the data was gathered and could easily do the same to get the most recent data possible.

### Plan
I'm going to use the code found here: https://www.kaggle.com/jacksoncrow/download-nasdaq-historical-data as a general guide to create my own code to retrieve all the stocks & ETFs traded on NASDAQ with the most recent price data available.

The following code was adapted from: https://www.kaggle.com/jacksoncrow/download-nasdaq-historical-data on 2/9/21

In [3]:
import pandas as pd

data = pd.read_csv('http://www.nasdaqtrader.com/dynamic/SymDir/nasdaqtraded.txt', sep='|')
data.head()

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
0,Y,A,"Agilent Technologies, Inc. Common Stock",N,,N,100.0,N,NaN,A,A,N
1,Y,AA,Alcoa Corporation Common Stock,N,,N,100.0,N,NaN,AA,AA,N
2,Y,AAA,Listed Funds Trust AAF First Priority CLO Bond...,P,,Y,100.0,N,NaN,AAA,AAA,N
3,Y,AAAU,Goldman Sachs Physical Gold ETF Shares,P,,Y,100.0,N,NaN,AAAU,AAAU,N
4,Y,AAC.U,"Ares Acquisition Corporation Units, each consi...",N,,N,100.0,N,NaN,AAC.U,AAC=,N

In [7]:
data.describe(include='all')

,Nasdaq Traded,Symbol,Security Name,Listing Exchange,Market Category,ETF,Round Lot Size,Test Issue,Financial Status,CQS Symbol,NASDAQ Symbol,NextShares
count,9827,9826,9826,9826,9826,9826,9826.000000,9826,4139,5687,9826,9826
unique,3,9826,9800,6,4,3,NaN,2,2,5687,9826,2
top,Y,BSCM,NYSE Test One Common Stock,Q,,N,NaN,N,N,RALS,BSCM,N
freq,9825,1,6,4139,5687,7464,NaN,9792,4037,1,1,9822
mean,NaN,NaN,NaN,NaN,NaN,NaN,99.888256,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,3.197953,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN

In [8]:
data['Test Issue'].value_counts()

N    9792
Y      34
Name: Test Issue, dtype: int64